language: rust
rust:
  - nightly

cache:
  cargo: true
  directories:
    - edit-frontend/node_modules/

addons:
  firefox: "latest"

node_js: 
  - "stable"

branches:
  only:
    # Enable building pull requests.
    #- master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    
    # Greenkeeper
    - /^greenkeeper/.*$/

before_install:
  # Install geckodriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

  # Install commands
  - command -v diesel || cargo install --debug diesel_cli --no-default-features --features sqlite-bundled
  
  # Test node version
  - node -v

script:
  # Prepare X service
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait to start
  
  # Check travis mode type
  - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then echo 'nightly' > rust-toolchain; fi

  # Run test
  - ./tools build

  # TODO consolidate these tests
  - cd oatie && cargo test && cd ..
  - cd edit-common && cargo test && cd ..
  - ./tools test
