language: rust
cache: cargo
rust:
  - nightly
addons:
  firefox: "latest"

before_install:
  # Install geckodriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

  # Install commands
  - command -v cargo-script || cargo install cargo-script
  - command -v diesel || cargo install diesel_cli --no-default-features --features sqlite
  - cargo install wasm-bindgen-cli -f
  - command -v mdbook || cargo install mdbook

  - rustup target add wasm32-unknown-unknown

  - cd edit-frontend; npm i; cd ..

script:
  # Prepare X service
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait to start

  # Run test
  - ./x.rs build
  - ./x.rs test
